- README.md
> Added very important question!

- README.md
There's a fair battle between CSS animation and javascript animation in the industry. Both have pro's and con's - would be good to know that a candidate is aware of more than one technique.
> Added js / css animation question to general

- README.md
> Add general question about a recent technical challenge

- Translations/Romanian/README.md
I've went through the english README today and aligned the roumanian translation to the current content. I've also corrected some translation mistakes I made originally.
> Align roumanian translation to the content at Sunday, January 11, 2015

- README.md
Unless capitalized coffee was intentional....
> Fix grammar/capitalization

- CONTRIBUTING.md
Issue: Spelling error in CONTRIBUTING.md #235
> Contributing issue tracker typo

- README.md
"As a potential employer I whant my coders to know how to quickly find out if a certain Browser/Version combination supports a certain web technique."
Rebase to https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/193
cc: @doertedev @darcyclarke
> Question added to X-Browser compatibility lookups

- README.md
More questions could probably be brought into this section, but this is a starting point nonetheless. 
Closes https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/227. 
Any questions/concerns here?
> Add HTTP/Network section

- README.md
One of my favorite interview questions. You'd be surprised how many interviewees messed this up.
An excellent answer (and discussion) can be found [on StackOverflow](https://stackoverflow.com/questions/3698200/window-onload-vs-document-ready). 
I'm not sure if this question belongs to JavaScript or jQuery though -- it's a bit of both.
> Added a JS q regarding window.onload and $(document).ready()

- README.md
Following up a question like "What are the advantages..." with a question that starts "If so..." makes no sense. This change removes the "If so" part.
> Reword CSS preprocessor question

- README.md
There's a question about CSS reset, and I think it may worth adding another following it: 
>What's the difference between "resetting" and "normalizing" CSS? Which would you choose, and why?
From my experience, a few developers only use one or another (which is fine) and can't really tell the difference.
The "why" part can also lead to an interesting open discussion, like [this](https://stackoverflow.com/questions/6887336/what-is-the-difference-between-normalize-css-and-reset-css), where interviewers can better evaluate the candidate's CSS understandings.
> Amended a sub-question into CSS reset

- README.md
> Removed the extra backtick

- README.md
Sorry for being nitpicking again. So we have this JS question:
> Describe the difference between cookies, sessionStorage and localStorage.
Technically there's nothing wrong with this very interesting question. Only, I spotted (I think) a very minor terminology problem here: When `sessionStorage` and `localStorage` are JS (`window`) objects, "cookies" is not -- we only have `document.cookie`, not `cookies`. Combining them in one  sentence thus doesn't seem right.
I've come up with 3 options for this:
1. Describe the difference between cookies, session storage and local storage.
1. Describe the difference between `cookie`, `sessionStorage` and `localStorage`.
1. Describe the difference between `cookie`s, `sessionStorage` and `localStorage`.
and went with the 2nd. What do you guys think?
> Standardizing wordings for `cookie vs sessionStorage vs localStorage` question

- README.md
Per: https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/242
> Promises question

- README.md
Add couple of questions to test basic concepts (coding, and networking).
> Add coding and networking questions

- README.md
> Expanding relatively obscure acronyms, re-phrasing questions

- Translations/Spanish/README_ES.md
Still a few updates remaining to synchronize, but it's much closer now.
> Updates to Spanish translation, removing hints/answers/examples and jQuery

- README.md
Why do we have 2 questions that look almost the same?
> Can you explain the difference between GET and POST?
> Can you explain the difference between GET and HEAD?
My guess: Maybe comparing GET and POST, and GET and HEAD ([haha](http://languagelog.ldc.upenn.edu/myl/GardnerFishAndChips.png)) as pairs, each makes more sense than comparing POST and HEAD. But still, shouldn't one question about HTTP methods be enough?
> Merge the two questions about get, post, and get into one

- README.md
A [good article](http://www.ebaytechblog.com/2014/12/08/async-fragments-rediscovering-progressive-html-rendering-with-marko/#.VQaViRCUe58) by Patrick Steele-Idem explained this concept very well.
> Add progressive rendering question

- README.md
I think it would be nice to expand the Promises section here, if and when to prefer them over callbacks
> Expand questions on promises: What are the pros and cons of using promises vs callbacks?

- Translations/French/README.md
Added / removed some items to match the english version.
Answers removed.
> French translation update

- README.md
A minor change to increase the readability of the document.
> Change "built in" to "built-in"

- README.md
The commit message should be descriptive enough :)
> Add a js question

- Translations/Italian/README.md
The Italian translation had not been updated in almost two years.
> Updated Italian translation for the General questions

- Translations/Italian/README.md
Updated Italian translation for the HTML questions.
> Updated Italian translation for the HTML questions

- README.md
Added following questions:
1. CORS question to General questions
2. selector (difference between .one.two and .one .two selectors) question to CSS Questions
3. Questions regarding debug and loops to JS Questions
> Add questions regarding CORS, CSS Selectors, JS Debug and JS loops

- README.md
"undeclared" is not actually a keyword in JS and shouldn't be styled as code.
> un-backticked "undeclared"

- README.md
- Translations/Indonesian/README.md
- The document in Indonesian was horribly translated by `google translate`. It was also a little outdated in comparison to its english version.  My changes are mostly fixing weird sentences and keeping the doc up to date. Hopefully it is more legible now for Indonesian readers. :tada: 
- While I am at it, I added a couple of missing links to the table of content for english version. And fix a little typo for consistency. :smile:
> Fix indonesian translation

- README.md
Adds two questions related to the event loop and synchronous/asynchronous task execution in JavaScript.
> Event loop questions.

- Translations/Indonesian/README.md
Just fixing typo.
Issue raised here: https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/311#commitcomment-12723009
cc: @rhonyabdullah / @appleboy
> Indonesian - typo correction

- Translations/Chinese/README.md
Update Chinese translation to match the latest English version.
> Update Chinese translation

- Translations/Romanian/README.md
* Fixes some mistakes in the translation
* Adds, based on master, all the extra questions/code added since the last update
> update and fix romanian translation based on master

- Translations/Spanish/README.md
General update for spanish translation.
> Update spanish translation

- Translations/Chinese-Traditional/README.md
Update Chinese-Traditional translation to the latest english version.
> update chinese traditional translation

- Translations/Portuguese/README.md
fix a small typo in portuguese translation
> fix portuguese typo

- README.md
This is one of my favourite questions that I ask myself. This justifies if a person really knows what are the actual powers of AJAX.
From here, we can move towards JSONP question since for someone who knows the limitations of ajax would definitely know something about or at-least heard about JSONP.
> Added advantages & disadvantages of using ajax

- README.md
https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded
> Don't use jQuery specific terms

- README.md
full standards mode, almost standards mode and quirks mode.
https://developer.mozilla.org/en-US/docs/Quirks_Mode_and_Standards_Mode
> Quirks Mode e Standards Mode

- README.md
I've found this "community and inspiration" question to be very good at broadening the conversation. The basic idea is to ask the interviewee for role model / mentor / references within the front-end community.
They usually respond with a person, podcast or sometimes conferences they've attended. Also makes them able to talk about how they keep up with the trends and evolution of practices.
Not attached to this particular phrasing but think it's important to touch on people's relation with the front-end community, and there isn't any question on that topic yet.
> Add "fun" question on inspiration, role models and mentors in our community

- README.md
Is there any differences between `function foo() {}` and `var foo = function() {}`
> Added JS question for differences of named function and anonymous function

- Translations/Korean/README.md
- update new questions.
- deprecated old qustions.
- refactor categorys position.
> Update korean translation

- Translations/Czech/README.md
> Fix markdown of Czech translation

- Translations/Arabic/README.md
Hello everyone,
I have translated your fantastic work into Arabic. Please let me know if there is anything I can do to make this translation successfully merged into master.
cheer!!
Anas
> Arabic Translations Added

- Translations/Spanish/README.md
Many words had errors, so I fixed them one by one :)
> Fixed some spanish typos and orthography

- README.md
JSPerf gives a very good example code: https://jsperf.com/loop-vs-map-vs-foreach
For detailed explanation: https://medium.com/@manojsinghnegi/array-methods-explained-filter-vs-map-vs-reduce-vs-foreach-ea3127c6d319
> Add JS question for map vs forEach functions to loop in array

- README.md
Let's be honest here. All of these questions are seriously outdated and asked in any modern context is really weird. 
Quirks mode? Are we still dealing with issues of IE8 and Netscape? Show me a modern web application that is overly concerned about quirks mode? 
In regards to XHTML and XML, the official HTML5 spec was published in 2014 and had been in use for years prior. This spec is intended subsume HTML 4 XHTML. So, asking any one of these questions is to not inquire as to a person's current knowledge, but their useless historical knowledge. 
HTML5 allowed us to move on, this repo should allow us the same privilege.
> removes old questions

- README.md
This is an outdated technique and should never be asked in an interview. Even if your app uses sprites, don't ask this question. Don't put someone in a position to have to explain an out-dated technique that they may not even know and make the interview awkward.
> removes question about sprites

- README.md
I have had issue with this question for a long time. As this list of questions have evolved to include questions of greater theory and practice, this one has persisted past it's expiration date. 
If you really want to ask a question about a person's mettle on the subject of CSS, the a more appropriate question is like what I have submitted.
> replaces display property question

- README.md
This question is so vague that if used in an interview the scope of the return could be almost anything? 
I propose that this question be removed and new questions that are more to the point be added to replace it. These questions point to real issues in regards to front-end web development and would help create a more specific line of questions for the interview.
> removes uber vague question

- README.md
These techniques have fallen out of favor for some time and I'd argue that most coming-up front-end devs rarely, if ever, use these techniques any longer. 
The use of SVG and icon-fonts have essentially removed the use case that these techniques used to solve. 
If these questions are to serve a purpose of interviewing new developers who are solving current problems, this question is not valid.
> removes image replacement question

- README.md
This question will only ever get a straw-man's argument at best. And this article [Responsive vs Adaptive Design – Which is Best for Mobile Viewing of Your Website?](http://mediumwell.com/responsive-adaptive-mobile/) only strengthens the position that there is now real difference between the two when it comes to coding a solution. Sure, there may be a design strategy here, but this is not a list of questions for designers. 
The replacement question gets to the core of the question about an actual implementation strategy for development. 
The expected answer from the question would be the expectation that the interviewee would understand that there is a significant different between coding a UI from a `desktop-first` perspective versus a `mobile-first` one. Also, this person would expect …
> updates responsive question

- README.md
Sorry ... it seems that with the confusion before that this question seemed to have made its way back in. Reference PR #428
Apologize for the confusion and in the future I will reduce the barrage of PRs.
> removes CSS sprites question ... again

- README.md
The operation is called a `Ternary operator`, not an expression. This PR updates that term. 
This question will determine a developer's understanding of the new function syntax. An interviewer would expect to hear answers like; reduced verbosity for creating anonymous functions and lexical scoping. 
This question is more focused at determining a developer's understanding of lexical scoping. 
Evaluating the general knowledge of a developer's understanding of higher-order functions. An interviewer would expect an answer along the lines of; 
1. a function that takes a function as an argument, or
1. a function that returns a function
An interviewer may also ask the developer to illustrate an example of a higher-order function. For example: 
```js
// a function that accepts a function as an …
```
> adds ES6 style questions

- README.md
Here is an addition to JS section: 4 questions about latest ES6 standard.
This question identifies if candidate is aware of rest syntax, which is the modern standard for handling parameters passed to a function. Explaining what is the problem with `arguments`, imo, should count as bonus points.
If a candidate knows in which cases to opt for spread syntax, it means that he/she is writing more concise, cleaner code (e.g. replacing apply).  Knowing the difference is really important since both syntaxes look exactly the same, but the aims are different.
This one tests candidate's knowledge about ES6 modules, which is an essential part of modern day web development.
The purpose is to elicit an explanation of "static vs. private", plus common use case for static class methods.
> adds a couple of ES6 related questions (partly addresses #421)

- LICENSE.md
I have updated the Licence.md date to 2018.
Fixes # (update licence date)
Simply look at the file LICENCE.md line 3.
> Keep licence up-to-date

- Translations/Turkish/README.md
Update Contributors and Getting Involved ("Dahil Olmak Icin") sections, correct formatting and broken link.
> Update Turkish translation

- .github/CONTRIBUTING.md
> Repare broken link to licence

- Translations/Korean/README.md
in Korea Translations have grammar error
docuemnt => document
i modify this grammar error
> grammar error

- Translations/Slovakian/README.md
> Minor grammar fix

- Translations/Turkish/README.md
Just little enhancement for turkish translate.md. Added anchor link for per title
> added anchor link for turkish translate

- questions/coding-questions.md
Add Promise microtask. The previous question only concerns about task execution queue, now I revise the code to make the question a little bit more challenging: You have to tell the difference between task and microtask.
Thanks!
> feat: add console.log in Promise microtasks

- questions/general-questions.md
> add general Q

- src/translations/slovakian/README.md
> Fixed some grammar in Slovak translation

- src/_includes/assets/css/content.css
- src/_includes/assets/css/header.css
- src/_includes/assets/css/navigation.css
- src/_includes/assets/js/app.js
- src/_includes/components/navigation.njk
- src/index.njk
* Made navigation responsive
* Added toggle button & JS to handle
* Styled button to match current design
* Changed container max-width (to accommodate nav width)
* Improved nav link styles:
* Highlight "current page"
* Icon for external links: clearer UI than previous overline
Fixes #509
Thanks!
> Responsive Nav

- src/questions/javascript-questions.md
Included the the `Array.` prefix in the question regarding `.forEach` and `.map` since the `.forEach` method reference is ambiguous and also used by array like built-in objects such as `NodeList` and HTML element collections. Updated the question regarding `.call` and `.apply` to reflect the same verbosity.
> Rephrased questions in javascript-questions.md to add context

- src/translations/bulgarian/README.md
- src/translations/danish/README.md
- src/translations/dutch/README.md
- src/translations/hungarian/README.md
- src/translations/italian/README.md
- src/translations/korean/Reference.md
- src/translations/latvian/README.md
- src/translations/romanian/README.md
- src/translations/serbian/README.md
- src/translations/slovakian/README.md
- src/translations/slovenian/README.md
replicates the work in #387 which has a million conflicts. I'd prefer to get that to work, but if I can't get that PR to work, I've got this one. This stuff actually needs to be fixed.
> Fixing headers for fun

- LICENSE.md
Keep licence up-to-date
Thanks!
> Keep licence up-to-date 

- src/_data/site.json
I _**think**_ this PR is correct/valid - but I haven't tested/built the site with this change.
Thanks!
> update URL of site

- package-lock.json
- package.json
```bash
npm audit
=== npm audit security report ===
found 0 vulnerabilities
in 9260 scanned packages
```
> Update dependencies according to security report

- src/_includes/components/footer.njk
update copyright year and change (c) to &copy;
> update copyright year and change (c) to &copy;

- src/questions/css-questions.md
**This PR welcomes changes/feedback**. The current question is a little dated as Flexbox is certainly not new and even Grid has been around for a while now. But if anyone has suggestions how this question can further be improved please feel free to leave feedback or edit this PR
> 'CSS Flexbox or Grid specs?' question update

- .github/CONTRIBUTING.md
> Add website instructions to CONTRIBUTING.md

- src/questions/general-questions.md
- src/questions/testing-questions.md
Added several questions to the  general list. 
- [ X] New Question
- [ X] My content follows the style guidelines of this project
- [ X] I have performed a self-review of my own content
> Updated questions

- package-lock.json
- src/questions/html-questions.md
Fix a sentence error on  html-questions.md. Changed "design" to "designing" on question number 3.
i.e 
What kind of things must you be wary of when design or developing for multilingual sites?
to
What kind of things must you be wary of when designing or developing for multilingual sites?
Thanks!
> Fix typo error on line 9: changed design to designing

- src/questions/fun-questions.md
While asking someone how they like their coffee might be fun or a nice (if a little weird) ice-breaker, I think it scarcely allows one to evaluate a candidate for a frontend position.
Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in …
> Remove irrelevant question

- src/questions/css-questions.md
> Updated css-questions.

- src/_includes/assets/css/content.css
- src/_includes/assets/css/header.css
- src/_includes/assets/css/variables.css
- src/_includes/layouts/default.njk
- src/index.njk
- src/translations/arabic/README.md
- src/translations/farsi/README.md
- src/translations/hebrew/README.md
Design fixes for RTL version
* Heading align to the right
* Use Arial font for RTL
Before:
After:
* Bullets fix
before:
After:
Thanks!
> fix(styles): design fixes for rtl

- src/questions/javascript-questions.md
> promise question

- src/translations/indonesian/README.md
Update the translation of indonesian language
I update the translation of General, HTML, CSS, JS, Testing, Performance, Network, and Fun Question
Thanks!
> Update Indonesian Language

- src/questions/html-questions.md
> Added - Question

- package-lock.json
- src/questions/css-questions.md
"What is the difference between CSS Grid and Flexbox? When would you use one over the other?"
> added new question in CSS

- src/translations/portuguese/README.md
fix: links to post blog
Broken link to post
Thanks!
> fix: links to post blog

- .github/dependabot.yml
> weekly dependabot to monthly

- .github/workflows/gh-pages-build.yml
> finally adding this action

- src/questions/javascript-questions.md
Added a question to the javascript-questions.md file about using OOP principles when coding with JavaScript. 
- [ x] New Question
- [x ] My content follows the style guidelines of this project
- [ x] I have performed a self-review of my own content
(Can you please add #hacktoberfest-accepted to the PR if you do accept it? Thank you!)
> Add a new question about OOP principles with JavaScript

- src/questions/general-questions.md
Added question:
- Can you explain what happens when you enter a URL into the browser?
> added general question

- src/translations/romanian/README.md
This is a fix for the few spelling mistakes for the Romanian translation markdown, and translate a question that was originally in English.
Thanks!
> Fix spelling errors and translate a question

- src/questions/javascript-questions.md
> Add Javascript question about truthy and falsy values

- src/_data/site.json
- src/index.njk
- src/translations/danish/README.md
> It once had Job in the title, but doesn't anymore

- src/translations/portuguese/README.md
Fixes #832 
Update Portuguese Translations to match template
> Update Portuguese Translations to match template

- src/questions/general-questions.md
I questions from my recent SWE interviews, most are very basic (ex. the SSR vs CSR one)
- [X ] My content follows the style guidelines of this project
> Added general questions

- src/translations/_template/README.md
> Fixing formatting and adding a question to the template

- src/translations/spanish/README.md
> Update Spanish Translations to match template (#838) 

- src/questions/css-questions.md
Saw this question while prepping for a SWE interview 
> Difference between fixed, fluid, responsive layouts

- src/translations/french/README.md
> feat(fr): Update French Translations to match template (#820)

- src/questions/css-questions.md
This particular question ends in a period but should be replaced with a question mark since it is asked like a question.
> replace with question mark in css-questions

- src/translations/german/README.md
Fixes #821 
This is my very first contribution. Excited and open to any feedback!
> Update German translation from issue #821
